env:
  browser: true
  es2021: true
extends: eslint-config-airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
"editor.tabSize": 4,
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
